<?php
/**
 * @file
 * Install, update and uninstall functions for the adm_trunk install profile.
 */

/**
 * Implements hook_install().
 */
function adm_install() {
  include_once DRUPAL_ROOT . '/core/profiles/standard/standard.install';
  standard_install();

  // Allow visitor account creation, but with administrative approval.
  \Drupal::configFactory()->getEditable('user.settings')->set('register', USER_REGISTER_VISITORS_ADMINISTRATIVE_APPROVAL)->save(TRUE);
}
