<?php

/**
 * @file
 */

/**
 * Implements hook_theme().
 */
function adm_core_theme($existing, $type, $theme, $path) {
  return [
    'adm_footer' => [
      'render element' => 'content',
    ],
  ];
}

/**
 * @return array
 */
function _adm_core_social_media_types() {
  $social = [
    'facebook' => 'Facebook',
    'twitter' => 'Twitter',
    'youtube' => 'Youtube',
  ];

  \Drupal::moduleHandler()->alter('adm_core_social_media_types', $social);

  return $social;
}