<?php
/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_views_view().
 */
function adm_media_preprocess_views_view(&$variables) {
  if ($variables['view']->id() === 'media_browser') {
    $variables['view_array']['#attached']['library'][] = 'adm_media/view';
  }
}

/**
 * Implements hook_form_alter().
 */
function adm_media_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if (strpos($form_id, 'entity_browser') === 0 && !empty($form['widget']['view'])) {
    // Style the submit button.
    $form['actions']['submit']['#value'] = t('Select media');
    $form['actions']['submit']['#attributes']['class'][] = 'entity-browser-modal-target';
  }
}
