<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function adm_media_theme($existing, $type, $theme, $path) {
  return [
    'adm_media_files_list' => [
      'variables' => [
        'files' => NULL,
        'items' => NULL,
        'title' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function adm_media_theme_suggestions_adm_media_files_list(array $variables) {
  $suggestions = [];
  /** @var \Drupal\Core\Field\FieldItemListInterface $items */
  $items = $variables['items'];

  if ($items !== NULL) {
    $field_definition = $items->getFieldDefinition();
    $entity = $items->getEntity();

    $suggestions[] = $variables['theme_hook_original'] . '__' . $field_definition->getName();
    $suggestions[] = $variables['theme_hook_original'] . '__' . $entity->getEntityTypeId() . '__' . $field_definition->getName();
  }

  return $suggestions;
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function adm_media_field_widget_entity_browser_entity_reference_form_alter(&$element, FormStateInterface $form_state, $context) {
  $element['#attached']['library'][] = 'adm_media/entity_browser';
}
