<?php

/**
 * @file
 */

use Drupal\Component\Serialization\Json;
use Drupal\Component\Utility\Html;
use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function adm_media_theme($existing, $type, $theme, $path) {
  return [
    'adm_media_files_list' => [
      'variables' => [
        'files' => NULL,
        'items' => NULL,
        'title' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function adm_media_theme_suggestions_adm_media_files_list(array $variables) {
  $suggestions = [];
  /** @var \Drupal\Core\Field\FieldItemListInterface $items */
  $items = $variables['items'];

  if ($items !== NULL) {
    $field_definition = $items->getFieldDefinition();
    $entity = $items->getEntity();

    $suggestions[] = $variables['theme_hook_original'] . '__' . $field_definition->getName();
    $suggestions[] = $variables['theme_hook_original'] . '__' . $entity->getEntityTypeId() . '__' . $field_definition->getName();
  }

  return $suggestions;
}

/**
 * Implements hook_preprocess_views_view().
 */
function adm_media_preprocess_views_view(&$variables) {
  if ($variables['view']->id() === 'media_browser') {
    $variables['view_array']['#attached']['library'][] = 'adm_media/view';
  }
}
