<?php

use Drupal\paragraphs\Entity\Paragraph;

/**
 * @param \Drupal\media\MediaInterface[] $media
 *
 * @return array
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function adm_default_content_create_default_front_paragraphs($media) {
  $paragraphs = [];


  return $paragraphs;
}
