<?php

/**
 * @file
 * Contains adm_admin.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function adm_admin_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the adm_core module.
    case 'help.page.adm_admin':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('ADM Administration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function adm_admin_preprocess_toolbar(&$variables) {
  $variables['#attached']['library'][] = 'adm_admin/toolbar';
}

/**
 * Implements hook_page_top().
 */
function adm_admin_page_top(array &$page_top) {
  if (isset($page_top['page_top']['node_preview'])) {
    if (($key = array_search('container-inline', $page_top['page_top']['node_preview']['#attributes']['class'], TRUE)) !== FALSE) {
      unset($page_top['page_top']['node_preview']['#attributes']['class'][$key]);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function adm_admin_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['langcode'])) {
    unset($form['langcode']['#options']['***LANGUAGE_site_default***'],
      $form['langcode']['#options']['***LANGUAGE_language_interface***'],
      $form['langcode']['#options']['***LANGUAGE_language_content***']);
  }

  if (isset($form['search_api_language'])) {
    unset($form['search_api_language']['#options']['***LANGUAGE_site_default***'],
      $form['search_api_language']['#options']['***LANGUAGE_language_interface***'],
      $form['search_api_language']['#options']['***LANGUAGE_language_content***']);
  }
}
